rm(list=ls())
search()
getwd()
setwd("C:\\Users\\tanveer.khan\\Desktop\\statistical learning")
list.files()
advertising <- read.csv("Advertising.csv",header=T)
cor(advertising)
attach(advertising)
names(advertising)
sales_tv <- lm(Sales~TV)
plot(TV,Sales,xlab="TV",ylab="Sales",main="TV-SALES")
abline(sales_tv)
sales_radio <- lm(Sales~Radio)
plot(Radio,Sales,xlab="Radio",ylab="Sales",main="Radio-SALES")
abline(sales_radio)
sales_newspaper <- lm(Sales~Newspaper)
plot(Newspaper,Sales,xlab="Newspaper",ylab="Sales",main="Newspaper-Sales")
abline(sales_newspaper)